spring:
  output:
    ansi:
      enabled: ALWAYS
  application:
    name: unlucky
  data:
    mongodb:
      uri: mongodb://localhost:27018
      database: unlucky
  security:
    oauth2:
      resource-server:
        jwt:
          jwk-set-uri: http://localhost:3333/realms/quickstart/protocol/openid-connect/certs
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:3333/realms/quickstart
        registration:
          keycloak:
            client-id: backend-service
            client-secret: 8TLHULwDPODzRyh8nmgoNkAbKRqwihiX
            scope: openid
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/keycloak"

keycloak:
  realm: quickstart
  client: admin-cli
  auth-server-url: http://localhost:3333
  credentials:
    secret: 4sxFSXY9im4MudET1Sa2XruBnAnh6E7y
