spring:
  output:
    ansi:
      enabled: ALWAYS
  application:
    name: unlucky
  datasource:
    url: jdbc:postgresql://localhost:5432/unlucky
    username: postgres
    password: mysecretpassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      resource-server:
        jwt:
          jwk-set-uri: http://localhost:3333/realms/quickstart/protocol/openid-connect/certs
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:3333/realms/quickstart
        registration:
          keycloak:
            client-id: backend-service
            client-secret: MhWCD0tqXxUWCtvwyQnTmqtHBoRED0qH
            scope: openid
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/keycloak"

keycloak:
  realm: quickstart
  client: admin-cli
  auth-server-url: http://localhost:3333
  credentials:
    secret: XFMMQDz9pSfQSZtdutO1NBr03xPvcxuX
