spring:
  profiles:
    active: dev
  output:
    ansi:
      enabled: ALWAYS
  application:
    name: unlucky
  datasource:
    url: jdbc:postgresql://localhost:5432/unlucky
    username: your_username
    password: your_password
    driver-class-name: org.postgresql.Driver
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: false
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      resource-server:
        jwt:
          jwk-set-uri: http://keycloak:8080/realms/quickstart/protocol/openid-connect/certs
      client:
        provider:
          keycloak:
            issuer-uri: http://keycloak:8080/realms/quickstart
        registration:
          keycloak:
            client-id: backend-service
            client-secret: fQLfbDrSRHTcIgFiR24YE1YWwp1t1xC7
            scope: openid
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/keycloak"

keycloak:
  realm: quickstart
  client: admin-cli
  auth-server-url: http://keycloak:8080
  credentials:
    secret: 3zLcfw6pRuJM6aHOJokaTtGFtBQh7QNu
